# Generated by Django 4.1 on 2022-08-06 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="content",
            old_name="modules",
            new_name="module",
        ),
    ]
